version: '2'

services:
  nginx:
      build: ./nginx
      ports:
        - "80:80"
      links:
        - php-fpm
      volumes_from:
        - php-fpm
      volumes:
        - ./logs:/var/log/nginx

  php-fpm:
      build: ./php-fpm
      ports:
        - "9000:9000"
      volumes:
        - ./..:/var/www
      links:
        - mysql
      command: composer install && php bin/console doctrine:schema:update -f

  mysql:
    build: ./mariadb
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=root
      - MYSQL_PASSWORD=skycop
      - MYSQL_ROOT_PASSWORD=skycop
    ports:
      - "3306:3306"
